### ISSUE TITLE
v0.10.14 too buggy

### ISSUE THREAD

**Issue by bottleblue** [TheFantasticWarrior/chrome-extension-imagus#30]
It's not really working properly on Firefox. Sometimes it will stop working completely. Images won't pop out. The settings window won't load, it's just a blank white screen. I have to restart Firefox to make it work again. 

One time I selected multiple sieves to disable. I press disable button and only one of them would disable. 

Update Sieves button doesn't work, still gets stuck on Loading. Importing sieves doesn't have function to save the enable/disable state. 

I have to go back to 0.10.11.

**Comment by kuzn123** [comment]
If there are problems with 0.10.14, it is recommended to reinstall it, re-configure it manually **(rather than importing old settings from a previous version - they are most likely incompatible)** and then import the [sieves](http://forum.ru-board.com/topic.cgi?forum=5&topic=50874&start=0&limit=1&m=5#1). And do not forget to click the "Save" button to consolidate the changes made.

Personally, this version works very well for me on both FF and Chrome.

**Comment by BoboceaOctavian** [comment]
Unfortunately that does not solve the issue. I've done a re-install and manual re-configuration, saved on every step, yet the extension still randomly stops working. There is no error message displayed, but no images are enlarged on any site (not even the load icon appears) and the extensions settings open as a blank page with no content (although there is html content in it if you view it's source). The fastest way I have found to resolve the issue is to disable and re-enable the Imagus mod in the Firefox manager.

**Comment by TheFantasticWarrior** [comment]
https://github.com/TheFantasticWarrior/chrome-extension-imagus/releases/tag/v0.10.14.2 probably is solved but im not sure, please help me test it

**Comment by BoboceaOctavian** [comment]
I've run this new version for a few hours tonight and I did not encounter the problem any more, so the fix seems promising. Hope it works for others too.

**Comment by bottleblue** [comment]
How do I use Imagus after installing the temporary addon? It still shows the old version when I open settings.

**Comment by TheFantasticWarrior** [comment]
In about:addons disable the old one

**Comment by bottleblue** [comment]
heh ok I should have known that. I'll let you know how it goes

**Comment by bottleblue** [comment]
Seems to be working now

**Comment by TheFantasticWarrior** [comment]
great, uploaded to the store

**Comment by bottleblue** [comment]
> great, uploaded to the store

The not working problem came back with 0.10.14.3

Edit: It just happened with 0.10.14.2 also. Hmm maybe it wasn't completely fixed?

**Comment by TheFantasticWarrior** [comment]
Did you have issues with store 0.10.14.2, or did you only use the "temporary add-on"? I think it's something about updating from old versions instead of fresh install that causes the issue

**Comment by bottleblue** [comment]
It was the store version. After 0.10.14.3 stopped working I downgraded to store's  0.10.14.2 and it still happened.

**Comment by TheFantasticWarrior** [comment]
I mean before the .3 update did you use store .2 without problem or only temp add-on

**Comment by bottleblue** [comment]
Yea I used store .2 and didn't notice any problems.

**Comment by TheFantasticWarrior** [comment]
try installing latest update and import settings from earlier versions or in the [github release page](https://github.com/TheFantasticWarrior/chrome-extension-imagus/releases/download/v0.10.14.5/defaults.jsn)

**Comment by bottleblue** [comment]
k I'll try it out thx
